### PR TITLE
Short Test Completed

### PR DESCRIPTION
**Pull request by realbwoi**
I used a very brute force solution but it still gets the job done. Thanks for you time.

### CODE REVIEW

**Comment by octovinh** [comment]
Hi Orlando,

Thanks for taking the time to complete the short test! However, it's not working as designed. The thoughts are being added to the bottom of the page instead of the top of the page. If you check out the GIF, you'll see what the expected behavior looks like.

If you'd like, go ahead and update your PR.

-Vinh

**Review by realbwoi — COMMENTED** [review]
Updated my code to prepend the new content instead of append the content.

**Comment by realbwoi** [comment]
I didn't even see that happening in the GIF. I've made the change and
updated my PR. Thanks for clarifying!

**Comment by octovinh** [comment]
All good, thanks for the update. Someone from recruiting will be in touch.

**Pull request closed without merging**
