### PR TITLE
finished product

### PR DESCRIPTION
**Pull request by brandonin**

### CODE REVIEW

**Comment by octovinh** [comment]
Hello there! Thanks for your submittal!

Can you describe the usage of the prepend.js and script.js files?

Thanks!

**Comment by brandonin** [comment]
Hey Vinh,

So initially I just threw everything within a <script> tag in order to make sure that it works. Then I decided to modularize everything so that the code would be easily read and reusable. I come from a very Angular background so I like to modularize thing using an MVC framework. The script.js will act as a controller and handle anything that deals with dom manipulation. The prepend.js file uses OOP and divides the into smaller pieces so that we can reuse “prepend.getFormValue” in case we want to for example send that data off to our servers, or if we need to use ‘prepend.getSeconds’ in another part of our app. The prepend would be our Model in MVC because it has most of the logic and would usually interact with a backend. I was thinking about adding TDD with Jasmine, but I think it would have been a bit overkill.

Brandon

**Comment by octovinh** [comment]
Hi Brandon,

Thanks for the clarification. You pass. Please send your resume over to recruiting@ontraport.com and someone will be in touch with you soon!

-Vinh

**Comment by brandonin** [comment]
Hey Vihn!

Thanks a lot. I’ve sent my resume!

Brandon In

**Pull request closed without merging**
