### PR TITLE
my Code

### PR DESCRIPTION
**Pull request by oooharuooo**
this is my solution. Let me know if you need anything!!!

### CODE REVIEW

**Comment by jebaird** [comment]
Howdy! Thanks for taking the time to complete the test. Recruiting will be in touch with you soon.

**Comment by octovinh** [comment]
Hi there,

I'm going to open this PR back up. The code doesn't quite work as expected. Can you read back through the instructions and watch the example video?

Then please re-submit your solution.

Thanks.

**Comment by oooharuooo** [comment]
@octovinh 
Sorry, I didn't pay attention to the display section. I just fixed it, please let me know if you have any questions !

**Comment by octovinh** [comment]
Rad, thanks for taking the time to update your solution. Recruiting will be in touch.

**Pull request closed without merging**
