### PR TITLE
front end test

### PR DESCRIPTION
**Pull request by premiumwd**
created test for submission

### CODE REVIEW

**Comment by LorenzoGangi** [comment]
pass, would you mind taking our long test https://github.com/Ontraport/frontend-interview-test-long. Also make sure Sara shetyonk@ontraport.com has your resume.

**Comment by premiumwd** [comment]
Hi Lorenzo,

question. Is the format of the json jsonp? Can I reorganize the json?

**Comment by LorenzoGangi** [comment]
You shouldn't need to change the json. If you are facing a problem and you need to change something about the test to get it to work, by all means do so. But please document your changes and provide reasons as to why you had to make the changes.

**Comment by premiumwd** [comment]
Thanks Lorenzo,

I am going to decline further involvement in your interview process. Please
update your long front end test to reflect the person's job duties.
Generalizing will prompt remorse.

**Pull request closed without merging**
