### PR TITLE
Steve Cleary Front-End Short Test

### PR DESCRIPTION
**Pull request by storbang**
Hello, I have completed the test. I will send a link to this pull request along with my resume in another email. 

Thanks! 

-Steve

### CODE REVIEW

**Comment by octovinh** [comment]
Hi Steve. Thanks for submitting your test. However, we can't pass you since we are expecting a solution that does not post to the server.

**Comment by storbang** [comment]
That's fine, though I don't really follow you. My solution is all done in Javascript and JQuery.

Please send me a solution that doesn't post to the server for my own future reference.

Thanks,

-Steve

**Comment by ray-peters** [comment]
Hey Steve, as requested: https://gist.github.com/ray-peters/a3f457c5ad78596f976f

Thanks again for your submission. Feel free to contact me if you have any questions.

Sincerely,
-R

**Comment by storbang** [comment]
Return false;

Thanks for that :-)

**Pull request closed without merging**
