### PR TITLE
Brief Test

### PR DESCRIPTION
**Pull request by red2678**
Hi. 

I have added the jQuery lib and captured the form's submit action. Calling event preventdefault I stopped the normal behavior and then dynamically create a P tag with the contents of the input (traversing down the DOM with .children() instead of making a new JQ call) appending the hyphen and the seconds. I modified 0% of the HTML and used context, tags and attribute selectors to get to what was needed. I saw no need to make an external JS file, one less HTTP request :)

### CODE REVIEW

**Comment by red2678** [comment]
Just a note, I coded to the exact specs as are in the description. I did not clear the textbox after an entry, or check for an empty input for example. Did you guys want that? As an experienced FED, I code to exactly what the task says. There is very little room for interpretation (at least that is the way it is at my current job). Please let me know if there is anything else you guys would like me to do.

**Comment by octovinh** [comment]
Nice job. Thanks for your attention to detail. Can you take a shot at our long test?https://github.com/Ontraport/frontend-interview-test-long

Also make sure Sara has your resume if you didnt apply through our careers site. shetyonk@ontraport.com

**Comment by red2678** [comment]
Thanks @octovinh. I'll send in my resume and move on to the long test.

**Comment by Shetyonk** [comment]
Hey @red2678 , 

Can you please also send me the contact information fo ryour recruiter? Thank you!

Best, 
Sara Hetyonk
Recruiting Coordinator
ONTRAPORT
shetyonk@ontraport.com

**Pull request closed without merging**
