### PR TITLE
Front-end Test by Patryk Pawłowski

### PR DESCRIPTION
**Pull request by bypatryk**
Hey Ontraport! Check my vanillaJS solution, hope we can work together! :)

### CODE REVIEW

**Comment by octovinh** [comment]
Nice, you pass. Please send your resume over to recruiting@ontraport.com and someone will be in touch with you soon!

**Comment by bypatryk** [comment]
Hey @octovinh, I sent my application 2 weeks ago and still didn't get any response. How long does it usually take? ;)

**Comment by octovinh** [comment]
My apologies for the delay @bypatryk. I'll follow up with recruiting and figure out what happened.

**Comment by bypatryk** [comment]
Thanks @octovinh! Looking forward to hearing from you :)

**Pull request closed without merging**
